### ISSUE TITLE
FastAPI + Ormar + Alembic + FactoryBoy

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/website#2]

**Comment by AXGKl** [comment]
can't wait ;-)

**Comment by pawamoy** [comment]
Gunther, your docutools project is amazing! I couldn't sleep last night, so decided to click on each one of the screenshot, and was like "wow", "jesus", "damn, this is incredible" :smile: 

Literate programming for as a Markdown extension was definitely something I wanted to create (though I didn't know about the "literate programming" concept), and now I get it for free! Awesome :smile: I'll try it out very soon and will probably include it in my copier-pdm template!

**Comment by pawamoy** [comment]
A bit late, but I eventually wrote that post last year: https://pawamoy.github.io/posts/testing-fastapi-ormar-alembic-apps/ :slightly_smiling_face: 

---

You might have noticed, I also eventually got to write my own "literate programming" Markdown extension, [Markdown Exec](https://pawamoy.github.io/markdown-exec/). Docutools was a great source of inspiration for it, so thanks!

Also also, hope you're doing well :smile:
