### ISSUE TITLE
No nav items in mobile nav drawer

### ISSUE THREAD

**Issue by sisp** [pawamoy/website#7]
Just a quick heads-up that the mobile nav drawer contains no nav items, so navigating your site isn't possible on mobile devices. This is because you're hiding the nav list to keep the content width while not showing the sidebars (on desktop screens):

https://github.com/pawamoy/website/blob/39bc50711c12dc0f47cbf541725fdd1c0017a14b/docs/index.md?plain=1#L12-L16

I think you could make this work by wrapping this override with a media query to apply it only on screen sizes that show the regular nav header.

**Comment by pawamoy** [comment]
Oh damn, you're right 😨 Thank you so much! I'll try to use a media query 👍

**Comment by pawamoy** [comment]
Fixed in 85743f32edf0879e60dce8d8550ac1e7b6c14e7b, thanks again!
